sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t osakiminky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true osakiminky/react-test npm run test

after_success:
  - docker build -t osakiminky/multi-client ./client
  - docker build -t osakiminky/multi-nginx ./nginx
  - docker build -t osakiminky/multi-server ./server
  - docker build -t osakiminky/multi-worker ./worker
#  Log into docker CLI - Create Environment Variables in TravisCI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
# Take all images and push to Dockerhub
  - docker push osakiminky/multi-client
  - docker push osakiminky/multi-nginx
  - docker push osakiminky/multi-server
  - docker push osakiminky/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: elasticbeanstalk-us-east-1-631217528309
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  