sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t king/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true king/react-test npm run test

after_success:
  - docker build -t client ./client
  - docker build -t nginx ./nginx
  - docker build -t server ./server
  - docker build -t worker ./worker
#  Log into docker CLI - Create Environment Variables in TravisCI
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
# Take all images and push to Dockerhub
  - docker push osakiminky/multi-docker:client
  - docker push osakiminky/multi-docker:nginx
  - docker push osakiminky/multi-docker:server
  - docker push osakiminky/multi-docker:worker


  
  